[project]
name = "scraping-agent"
version = "0.1.0"
license = "Apache-2.0"
license-files = ["LICENSE"]
description = "An agent for automated web search and scraping using local language models"
readme = "README.md"
authors = [
    { name = "Aman Kumar Singh", email = "amankumarsingh.professional@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "browser-use>=0.13.8",
]

[project.scripts]
scraping-agent = "scraping_agent.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
